addons:
  sonarcloud:
    organization: guilhermepaciulli
    token:
      secure: "AiSZMB9rEXUh3gyjLMEqTioiWsfdzGQJkwPjKkFxrdUOrCAOADwLm/AJQdSK1Ceo9FL+8vYawszNvAiRoO2ueBSmddv5A7qN0Vs0vGjK7zzvtt/sCtcPRTppIwR5cp6DAUjFShYm9KvV78nM8M3+f6mROs6k0TWOp88iy87lBhOYt8zZZLrGFkysFJCYtjkL/t/vsAl3hTxRFBUfyS9kbMQ41Ntoj/EOYPjxLxDch9YuvbtGIRurHIq/c5cE6eepznbNEZfBk9HMYGI8OIAtVfblKqDZCtnLH1gLUudDXLq7NOeqx8ochgRm6XfO5mq587oX/7HvgFVTNhUGL7dxk6zKTnVMbmilGnOKnzT2HoJTb3Ha/go6rWeQIJwJrfSgocvlu5qnfgAzQLYP7HicxIA5ir0HTH7CE9m+xP/U8Kt3eXbKxXsWqUA3DAzozSxPeKLtIZXwkOFvfOrqB2zS6g0PUre6WLFCfm22dQym8KD5PKoh4NEcaVYQtmoYMZNIGzrjhDa971naWQCKblS8vm6B8kak1cFeQf/HFZCpnvQR/bONFk95riJ8qjGpSs3u+U0LzJ0wtX42faFGG1LCFWckQgXEHQ15Cp3W2Es5bAjIK60ZYHHq/5vzxMH+U5pWndq9IlkY6lSj6jNK7JDhwJwwH4MmwRpzHqTtEiP0Rb8="
language: swift
osx_image: xcode11.4
before_install:
  - gem install xcov
script:
  - cd C2C
  - fastlane tests
  - sh "xccov-to-sonarqube-generic.sh C2C/fastlane/*.xcresult > sonarqube-generic-coverage.xml"
  - sonar-scanner
