addons:
  sonarcloud:
    organization: guilhermepaciulli
    token:
      secure: C4CpDSqw/aXdNFFum53fdbkO/mccnYpW38YtYjICAlp5nfGwtZ4i7LqGwpTVgzZw4VJcyrenzuiL0UCe5ca+OqyJUUtxFud30oqWUbxI1rTEMq0c5tgzS3iCQdFQHRy9JdvEzYjCxTKEOFTsUXCJquKyNVQYZoidL/MLS7szN4SVe8dp82Eg+d3X1vWbtb2H88BA3BPDQx62riSGeXtmoGOgeWPsMDoAGtqe4o9T1qltPRxg6h9CaSfKuifVjOrUsEC+pcRNGCesrFTGBbv+9hwkpcZp4EU4h7hO5MuZFgYcMElWZYYQvbv110ehLQythJymCRzLFy8/FM5bGfnzHqEy1RvqQoEHIogKaNeKftARRYgPeMu079Gf3jg/Nw43GBQlqSZz1qHCmC443cP+TNG/sp1acok0z0O6DtqiUPV3uwrTr1SMQjMkqiQsyM6enAjh8B1T4z9ITOnZgV/F7tXL+UzPVe4V+bi1pPhk0xzosF7bT/7qf5v7iAYMZC7gdgodtRmj0c0VPhS2X6lPL7fSqXJSmHgBxEVHmhboNyFZLGvHiykBr2fDHkJV3QzO0VG7CBOcAn6Lyv0B7j2T7hZeQ9EulcIMIUpFXeXwFs3f6odpHuyIHreZ3zKtpQItQE8Sr16WW+vf/pzSzk9Evke5Am5NzIvgrw2SygSbzvM=
language: swift
osx_image: xcode11.4
before_install:
  - gem install xcov
script:
  - cd C2C
  - fastlane tests
  - sh "xccov-to-sonarqube-generic.sh ~/Library/Developer/Xcode/DerivedData/"
  - sonar-scanner
