# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'C2C' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for C2C
  pod 'Kingfisher'
  pod 'PromiseKit'
  pod 'SwiftLint'

  target 'C2CTests' do
    inherit! :search_paths
    pod 'Quick'
    pod 'Nimble'
  end

  target 'C2CUITests' do
    # Pods for testing
  end

end
