name: Swift

on:
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
        run: |
            gem install cocoapods
            cd C2C
            pod install --repo-update
    - name: Run tests
      uses: maierj/fastlane-action@v1.4.0
      with:
        lane: 'tests'
        subdirectory: 'C2C/fastlane'
