name: Swift

on:
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: macos-latest
    - name: Set XCode Version
      run: sudo xcode-select -s /Applications/Xcode_11.1.app
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      uses: maierj/fastlane-action@v1.4.0
      with:
        lane: 'tests'
        subdirectory: 'C2C/fastlane'
