name: Swift

on:
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install fastlane
      run: |
        brew install fastlane
    - name: Run tests
      run: |
        cd C2C/fastlane
        fastlane tests
