name: Swift

on:
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set XCode Version
      run: sudo xcode-select -s /Applications/Xcode_11.app
    - name: Install Dependences
      run: |
        cd C2C/
        pod repo update
        pod install
      shell: bash
    - uses: ty0x2333/cocoapods-action@master
      with:
        workspace: C2C/C2C.xcworkspace
        use_modern_build_system: true
        scheme: C2CTests
        lint: false
        additional_build_params: -destination 'platform=iOS Simulator,OS=13.0,name=iPhone 11'
